const books = {
  Genesis: require('../../assets/Bible-kjv-master/books/Genesis.json'),
  Exodus: require('../../assets/Bible-kjv-master/books/Exodus.json'),
  Leviticus: require('../../assets/Bible-kjv-master/books/Leviticus.json'),
  Numbers: require('../../assets/Bible-kjv-master/books/Numbers.json'),
  Deuteronomy: require('../../assets/Bible-kjv-master/books/Deuteronomy.json'),
  Joshua: require('../../assets/Bible-kjv-master/books/Joshua.json'),
  Judges: require('../../assets/Bible-kjv-master/books/Judges.json'),
  Ruth: require('../../assets/Bible-kjv-master/books/Ruth.json'),
  '1 Samuel': require('../../assets/Bible-kjv-master/books/1Samuel.json'),
  '2 Samuel': require('../../assets/Bible-kjv-master/books/2Samuel.json'),
  '1 Kings': require('../../assets/Bible-kjv-master/books/1Kings.json'),
  '2 Kings': require('../../assets/Bible-kjv-master/books/2Kings.json'),
  '1 Chronicles': require('../../assets/Bible-kjv-master/books/1Chronicles.json'),
  '2 Chronicles': require('../../assets/Bible-kjv-master/books/2Chronicles.json'),
  Ezra: require('../../assets/Bible-kjv-master/books/Ezra.json'),
  Nehemiah: require('../../assets/Bible-kjv-master/books/Nehemiah.json'),
  Esther: require('../../assets/Bible-kjv-master/books/Esther.json'),
  Job: require('../../assets/Bible-kjv-master/books/Job.json'),
  Psalms: require('../../assets/Bible-kjv-master/books/Psalms.json'),
  Proverbs: require('../../assets/Bible-kjv-master/books/Proverbs.json'),
  Ecclesiastes: require('../../assets/Bible-kjv-master/books/Ecclesiastes.json'),
  'Song of Solomon': require('../../assets/Bible-kjv-master/books/SongofSolomon.json'),
  Isaiah: require('../../assets/Bible-kjv-master/books/Isaiah.json'),
  Jeremiah: require('../../assets/Bible-kjv-master/books/Jeremiah.json'),
  Lamentations: require('../../assets/Bible-kjv-master/books/Lamentations.json'),
  Ezekiel: require('../../assets/Bible-kjv-master/books/Ezekiel.json'),
  Daniel: require('../../assets/Bible-kjv-master/books/Daniel.json'),
  Hosea: require('../../assets/Bible-kjv-master/books/Hosea.json'),
  Joel: require('../../assets/Bible-kjv-master/books/Joel.json'),
  Amos: require('../../assets/Bible-kjv-master/books/Amos.json'),
  Obadiah: require('../../assets/Bible-kjv-master/books/Obadiah.json'),
  Jonah: require('../../assets/Bible-kjv-master/books/Jonah.json'),
  Micah: require('../../assets/Bible-kjv-master/books/Micah.json'),
  Nahum: require('../../assets/Bible-kjv-master/books/Nahum.json'),
  Habakkuk: require('../../assets/Bible-kjv-master/books/Habakkuk.json'),
  Zephaniah: require('../../assets/Bible-kjv-master/books/Zephaniah.json'),
  Haggai: require('../../assets/Bible-kjv-master/books/Zephaniah.json'),
  Zechariah: require('../../assets/Bible-kjv-master/books/Zechariah.json'),
  Malachi: require('../../assets/Bible-kjv-master/books/Malachi.json'),
  Matthew: require('../../assets/Bible-kjv-master/books/Matthew.json'),
  Mark: require('../../assets/Bible-kjv-master/books/Mark.json'),
  Luke: require('../../assets/Bible-kjv-master/books/Luke.json'),
  John: require('../../assets/Bible-kjv-master/books/John.json'),
  Acts: require('../../assets/Bible-kjv-master/books/Acts.json'),
  Romans: require('../../assets/Bible-kjv-master/books/Romans.json'),
  '1 Corinthians': require('../../assets/Bible-kjv-master/books/1Corinthians.json'),
  '2 Corinthians': require('../../assets/Bible-kjv-master/books/2Corinthians.json'),
  Galatians: require('../../assets/Bible-kjv-master/books/Galatians.json'),
  Ephesians: require('../../assets/Bible-kjv-master/books/Ephesians.json'),
  Philippians: require('../../assets/Bible-kjv-master/books/Philippians.json'),
  Colossians: require('../../assets/Bible-kjv-master/books/Colossians.json'),
  '1 Thessalonians': require('../../assets/Bible-kjv-master/books/1Thessalonians.json'),
  '2 Thessalonians': require('../../assets/Bible-kjv-master/books/2Thessalonians.json'),
  '1 Timothy': require('../../assets/Bible-kjv-master/books/1Timothy.json'),
  '2 Timothy': require('../../assets/Bible-kjv-master/books/2Timothy.json'),
  Titus: require('../../assets/Bible-kjv-master/books/Titus.json'),
  Philemon: require('../../assets/Bible-kjv-master/books/Philemon.json'),
  Hebrews: require('../../assets/Bible-kjv-master/books/Hebrews.json'),
  James: require('../../assets/Bible-kjv-master/books/James.json'),
  '1 Peter': require('../../assets/Bible-kjv-master/books/1Peter.json'),
  '2 Peter': require('../../assets/Bible-kjv-master/books/2Peter.json'),
  '1 John': require('../../assets/Bible-kjv-master/books/1John.json'),
  '2 John': require('../../assets/Bible-kjv-master/books/2John.json'),
  '3 John': require('../../assets/Bible-kjv-master/books/3John.json'),
  Jude: require('../../assets/Bible-kjv-master/books/Jude.json'),
  Revelation: require('../../assets/Bible-kjv-master/books/Revelation.json'),
};

export default books;
